version: "3"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="renec"
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
