version: "3"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="renec"
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  # serve:
  #   image: node:16.20.0
  #   depends_on:
  #     - mongodb
  #     - redis
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: bash -c "npm run start:dev"