version: "3"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="renec"
    ports:
      - 27017:27017
    volumes:
      - 'mongodb_data:/data'

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - 'redis_data:/data'

  serve:
    image: neikop/renec-api:latest
    depends_on:
      - mongodb
      - redis
    ports:
      - 8080:8080


volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
